name = "eeloong"
compatibility_date = "2026-04-26"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "carousell-bot"
database_id = "d1571101-a141-4378-89c9-f5693a691a34"

[[kv_namespaces]]
binding = "STOCK_CACHE"
id = "f44fe446a2c54ac0a2fab56776f04077"
preview_id = "30a04d45a0834601a11222ec1249b851"